---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  labels:
    provider: aws
  name: this-eks-iam-role
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }

  providerConfigRef:
    name: aws-provider-config
  deletionPolicy: Delete
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  name: this-role-servicepolicy
spec:
  roleNameRef:
    name: this-eks-iam-role
  # wellknown policy arn
  policyArn: arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  name: this-role-clusterpolicy
spec:
  roleNameRef:
    name: this-eks-iam-role
  # wellknown policy arn
  policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider