---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  labels:
    provider: aws
  name: this-igw
spec:
  providerRef:
    name: dv-aws-provider
  deletionPolicy: Delete
  vpcIdRef:
    name: this-vpc