---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  labels:
    provider: aws
  name: this-igw
spec:
  forProvider:
    vpcIdRef:
      name: this-vpc
  providerRef:
    name: provider-aws
  providerConfigRef:
    name: aws-provider
  deletionPolicy: Delete
