---
apiVersion: ec2.aws.crossplane.io/v1alpha4
kind: RouteTable
metadata:
  name: this-routetable
spec:
  forProvider:
    vpcIdRef:
      name: this-public-vpc
    region: us-east-1
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: this-igw
    associations:
      - subnetIdRef:
          name: this-subnet-a
      - subnetIdRef:
          name: this-subnet-b
      - subnetIdRef:
          name: this-subnet-c
  deletionPolicy: Delete
  providerConfigRef:
    name: aws-provider-config