---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: this-vpc
spec:
  forProvider:
    cidrBlock: 192.168.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
  deletionPolicy: Delete
  providerRef:
    name: this-aws-provider